### PR TITLE
Cmake updates

### PR DESCRIPTION
**Pull request by LiamPattinson**
I've updated the CMake build system to allow the project to be installable and to permit the creation of either shared or static libraries. Installing the library makes it much faster to link with other projects, as you can use:

```
find_package(fdpapi)
```

and skip all of the `FetchContent` calls and compilation. I also cleaned up how some of the dependencies are handled, ensuring that all linking was `PRIVATE` where possible and using namespaced targets instead of directly linking libraries and including headers.

This was motivated by the development of a [C API](https://github.com/PlasmaFAIR/cDataPipeline), as I ran into difficulties creating a library that uses cppDataPipeline as a dependency. I'm currently using this branch as a submodule of [cDataPipeline](https://github.com/PlasmaFAIR/cDataPipeline). I'll be looking at creating a Fortran API in the new year.

## Known issues

- You can't install static libraries if Boost isn't installed on the user's system, as the standalone Boost::regex module doesn't provide its own export targets. It seems to work okay if you use shared libraries. This could be fixed by instead using a fork of the Boost::regex repo which _does_ include export targets, or falling back on built-in C++ regex.
- Haven't been able to test on Windows/Mac.
- Had to use a fork of DigestPP with a proper CMake build system. Unrelated to this PR, but I think it might be a good idea to switch this out for a more tried-and-tested library like OpenSSL (see also Issue https://github.com/FAIRDataPipeline/cppDataPipeline/issues/24). There's also [cryptopp](https://github.com/weidai11/cryptopp), but that also suffers from a seriously outdated project structure/build mechanism.
- Not something I think should be fixed by this PR, but the dependency GhcFilesystem is exposed at the top-level header file, so anything which uses this library strictly requires this package to be installed. This could be a problematic if you ever get to the point of distributing binaries, and it's not great for C++17+ users who are likely using `std::filesystem` instead. Solutions could include replacing it with `std::filesystem` and bumping the minimum C++ version to C++17 (which should be supported by all major compilers by now?), or converting to `std::string` at the top level to keep things as widely compatible as possible.

### CODE REVIEW

**Comment by RyanJField** [comment]
HI Liam, I have reviewed this and there are few minor changes needed to compile and install on windows and Mac, I'll put these in a branch, but first the biggest issue is BOOST regex. On windows it won't link even if compiled dynamically. The two options I see are including it as a submodule and adding it to the source (if BOOST regex is not found) or providing a export for boost (boost does have an export target but I can't get it to work properly). The reason we are using boost regex is because the machine being used to develop the BEEP model runs GCC 4.8 which while somewhat C++ compliant does not include regex. Open to suggestions.

**Comment by LiamPattinson** [comment]
I'll see what I can do, but I'm currently having some trouble sourcing a Windows machine I can test on. I might be able to find some time to test it on my home PC tomorrow, and failing that I could try debugging via GitHub Actions. I think the best option will be for us to provide export targets if Boost isn't found on the user's system.

**Comment by RyanJField** [comment]
I am currently using this branch: https://github.com/FAIRDataPipeline/cppDataPipeline/tree/cmake_updates to test it run actions automatically and test building on windows, Linux, Mac and GCC 4.8, currently it is linking using link directories (only to test installation on windows (manually) and would not recommend).

This branch has some windows specific fixes:
`CMAKE_INSTALL_LIBDIR` etc., are all GNU specific, so need to be defined if not using GNU:
[https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/src/CMakeLists.txt#L80](https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/src/CMakeLists.txt#L80)

The windows specific include paths were broken:
[https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/src/CMakeLists.txt#L28](https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/src/CMakeLists.txt#L28)

To install and use on windows (possibly Mac / non GNU), targets need to be found prior to loading the project targets:
[https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/cmake_modules/fdpapiConfig.cmake.in](https://github.com/FAIRDataPipeline/cppDataPipeline/blob/cmake_updates/cmake_modules/fdpapiConfig.cmake.in)
We should probably make them all required, if we're going to export boost regex as they all need to be installed for the package to work.

I also removed ghc_filesystem from the public header.

There maybe more but I can't think of any at the moment, the major issue is the boost regex.

You can either use this branch or merge your pull request onto a new branch to test with github actions, we will need to write a new action to test with the [cppSimpleModel](https://github.com/FAIRDataPipeline/cppSimpleModel) using installation (as well as fetch content), I have already modified the cppSimpleModel to try and find the fdpapi package [https://github.com/FAIRDataPipeline/cppSimpleModel/blob/main/src/CMakeLists.txt#L31](https://github.com/FAIRDataPipeline/cppSimpleModel/blob/main/src/CMakeLists.txt#L31), so it would just be a case of adding a new action which installs the fdpapi and then compiles and runs the cppSimpleModel.

Feel free to delete this branch if you merge your code onto a new branch.

**Comment by LiamPattinson** [comment]
Sorry for the lack of progress here -- still waiting to get a Windows machine, and I've been working on other projects in the meantime.

I had a quick look into why it was failing with GCC 4.8, and I think I may have found an easy solution, but I can't confirm without running actions. I'm seeing "Expected — Waiting for status to be reported" for all actions here, and I can't figure out what's causing it. Is the right solution here simply to close this PR and open a new one?

Looking into it, I'm not sure if I'll be able to make export targets for boost::regex if it's being grabbed as a standalone library. The easiest solution might be to make 'install fdpapi' and 'grab boost::regex using FetchPackage' mutually exclusive options, so installation will only work if the user already has Boost installed on their system.

**Comment by RyanJField** [comment]
> Sorry for the lack of progress here -- still waiting to get a Windows machine, and I've been working on other projects in the meantime.
> 
> I had a quick look into why it was failing with GCC 4.8, and I think I may have found an easy solution, but I can't confirm without running actions. I'm seeing "Expected — Waiting for status to be reported" for all actions here, and I can't figure out what's causing it. Is the right solution here simply to close this PR and open a new one?
> 
> Looking into it, I'm not sure if I'll be able to make export targets for boost::regex if it's being grabbed as a standalone library. The easiest solution might be to make 'install fdpapi' and 'grab boost::regex using FetchPackage' mutually exclusive options, so installation will only work if the user already has Boost installed on their system.

For security, actions won't run on a Pull Request from a fork. To get them to run, you will need to use a branch in this repo.

We do not want to require people to install boost manually if possible, I understand this is the easiest option but after discussion, it was decided it would be preferable to not do this.

The other option is to change the regex library. one compatible with GCC 4.8, Windows, Linux and Mac OS.

Hope this helps.

**Comment by RyanJField** [comment]
> > Sorry for the lack of progress here -- still waiting to get a Windows machine, and I've been working on other projects in the meantime.
> > I had a quick look into why it was failing with GCC 4.8, and I think I may have found an easy solution, but I can't confirm without running actions. I'm seeing "Expected — Waiting for status to be reported" for all actions here, and I can't figure out what's causing it. Is the right solution here simply to close this PR and open a new one?
> > Looking into it, I'm not sure if I'll be able to make export targets for boost::regex if it's being grabbed as a standalone library. The easiest solution might be to make 'install fdpapi' and 'grab boost::regex using FetchPackage' mutually exclusive options, so installation will only work if the user already has Boost installed on their system.
> 
> For security, actions won't run on a Pull Request from a fork. To get them to run, you will need to use a branch in this repo.
> 
> We do not want to require people to install boost manually if possible, I understand this is the easiest option but after discussion, it was decided it would be preferable to not do this.
> 
> The other option is to change the regex library. one compatible with GCC 4.8, Windows, Linux and Mac OS.
> 
> Hope this helps.

If you don't want to switch to a branch on this repo, you can add [pull_request / pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) to the `on` block of the two .github workflow yamls and then will be able to approve them being run.

**Pull request closed without merging**
