### PR TITLE
Cmake updates v2

### PR DESCRIPTION
**Pull request by LiamPattinson**
A follow up for PR https://github.com/FAIRDataPipeline/cppDataPipeline/pull/35. To get around issues with Boost::regex on GCC 4.8 and general installation issues, instead uses the regex library [re2](https://github.com/google/re2).

TODO:

Need to add a workflow that tests installation and the later use of `find_package(fdpapi)`.

### CODE REVIEW

**Comment by LiamPattinson** [comment]
I've had a go at getting everything installable and shifting the default behaviour to use installed components instead of downloading them fresh every time. Unfortunately, JsonCpp seems to be causing issues. It's possible to get around some of these by forcing the use of `FetchContent` by setting `FDPAPI_FETCH_JSONCPP_ONLY`, but not all.

- It breaks if users have `libjsoncpp-dev` installed on Ubuntu, as that's an old version which isn't compatible with FDP (I missed removing this install from the GCC 4.8 build, but I'll get that in with the next push). 

- Windows is failing to install JsonCpp in the actions, but it works on the machine I set up. I'll try to investigate this next week.

I'll also need to change the simple model test to try building from an installed library. I've made a [new branch of cppSimpleModel](https://github.com/FAIRDataPipeline/cppSimpleModel/tree/prevent_fetchcontent_option) that will allow me to test this. Should I make a PR for this?

Reminder to myself: I named a bunch of options `FDPAPI_FETCH_*_NEVER` and `FDPAPI_FETCH_*_ONLY`, but `FDPAPI_FETCH_*_ALWAYS` would have made more sense.

**Comment by LiamPattinson** [comment]
I think I've got everything working on Windows now, though GitHub Actions seem to be having trouble installing from Ubuntu repos at the moment.

**Comment by LiamPattinson** [comment]
I'm back to failing on the GCC 4.8 build, and I think it might be because it's using an old version of YAML-cpp. It's a similar problem to the JsonCpp issues I ran into earlier, so the solution should probably be the same. There are a few ways to fix this:

- Remove the `apt install libyaml-cpp-dev libjsoncpp-dev` bits.
- Set `-DFDPAPI_ALWAYS_FETCH_JSONCPP=ON -DFDPAPI_ALWAYS_FETCH_YAMLCPP=ON` in the workflows. This would ignore the `apt install` packages and get new ones from GitHub.
- Rewrite the code so that it works with whatever packages are shipped with the workflow runners (honestly, I'd rather avoid this option!)

The previous behaviour was to ignore the `apt install` packages and grab new ones using `FetchContent` in all cases, whereas now it's defaulting to `find_package` and only using `FetchContent` if it can't find anything. Either of the first two options would restore this behaviour.

**Comment by RyanJField** [comment]
> I'm back to failing on the GCC 4.8 build, and I think it might be because it's using an old version of YAML-cpp. It's a similar problem to the JsonCpp issues I ran into earlier, so the solution should probably be the same. There are a few ways to fix this:
> 
> * Remove the `apt install libyaml-cpp-dev libjsoncpp-dev` bits.
> * Set `-DFDPAPI_ALWAYS_FETCH_JSONCPP=ON -DFDPAPI_ALWAYS_FETCH_YAMLCPP=ON` in the workflows. This would ignore the `apt install` packages and get new ones from GitHub.
> * Rewrite the code so that it works with whatever packages are shipped with the workflow runners (honestly, I'd rather avoid this option!)
> 
> The previous behaviour was to ignore the `apt install` packages and grab new ones using `FetchContent` in all cases, whereas now it's defaulting to `find_package` and only using `FetchContent` if it can't find anything. Either of the first two options would restore this behaviour.

I have fixed the CI, I will manually install the API and run the simpleModel over the next couple of days to ensure the regex is working correctly, then I'll merge.

**Pull request merged**
